version: '2.0'
services:
  website:
    # 用来指定一个包含Dockerfile文件的路径。一般是当前目录. 。Fig将build并生成一个随机命名的镜像
    build: .
    # 镜像
    image: wkqb-web:0.0.1
    # 容器名称
    container_name: wkqb-web
    # 指定与部署和运行服务相关的配置（restart: always关机或者重启docker同时重启容器）
    restart: always
    # 挂载目录
    volumes:
      - dist/:/usr/share/nginx/html/
      - default.conf:/etc/nginx/conf.d/default.conf
    # 映射端口 将1307端口映射到主机80端口
    ports:
      - "8888:80"
    # 覆盖容器启动后默认执行的命令
    command: "/bin/bash -c \"envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'\""
